/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class KonversiBilanganBiner extends javax.swing.JFrame {

    /**
     * Creates new form KonversiBilanganBiner
     */
    public KonversiBilanganBiner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hasildes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        convertdes = new javax.swing.JButton();
        convertbin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        hasilbin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        hasildes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasildesActionPerformed(evt);
            }
        });
        getContentPane().add(hasildes);
        hasildes.setBounds(80, 80, 350, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Decimal");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 80, 70, 30);

        convertdes.setText("Convert to Decimal");
        convertdes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertdesActionPerformed(evt);
            }
        });
        getContentPane().add(convertdes);
        convertdes.setBounds(80, 140, 140, 30);

        convertbin.setText("Convert to Biner");
        convertbin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertbinActionPerformed(evt);
            }
        });
        getContentPane().add(convertbin);
        convertbin.setBounds(260, 140, 170, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Biner");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 210, 60, 30);

        hasilbin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilbinActionPerformed(evt);
            }
        });
        getContentPane().add(hasilbin);
        hasilbin.setBounds(80, 210, 350, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Binary and Decimal Converter");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 0, 250, 50);

        setBounds(0, 0, 461, 502);
    }// </editor-fold>//GEN-END:initComponents

    private void convertdesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertdesActionPerformed
try{
        String biner = hasilbin.getText();
        if(biner.isEmpty()){
            throw new NullPointerException("Field can't be empty");
        }
        int bil = Integer.parseInt(biner, 1);
        String bilcon = String.valueOf(bil);
        hasildes.setText(bilcon);
}catch(NullPointerException e){
        JOptionPane.showMessageDialog(null,e.getMessage(),"Failed",JOptionPane.WARNING_MESSAGE);
}catch (Exception npe){
        JOptionPane.showMessageDialog(null,"Field can't filled by alphabet" ,"Failed",JOptionPane.WARNING_MESSAGE);
    }

 
    }//GEN-LAST:event_convertdesActionPerformed

    private void convertbinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertbinActionPerformed
    try{
        String awal = hasildes.getText();
        if(awal.isEmpty()){
            throw new NullPointerException("Field can't be empty");
        }
        int bil = Integer.parseInt(awal);
    
    String bin = Integer.toBinaryString(bil);
    
    hasilbin.setText(bin);}
    catch(NullPointerException e){
     JOptionPane.showMessageDialog(null,e.getMessage() ,"Failed",JOptionPane.WARNING_MESSAGE);    
    }
    catch(NumberFormatException nfe){
        JOptionPane.showMessageDialog(null,"Field can't filled by alphabet" ,"Failed",JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_convertbinActionPerformed

    private void hasildesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasildesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasildesActionPerformed

    private void hasilbinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilbinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilbinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiBilanganBiner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiBilanganBiner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiBilanganBiner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiBilanganBiner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiBilanganBiner().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convertbin;
    private javax.swing.JButton convertdes;
    private javax.swing.JTextField hasilbin;
    private javax.swing.JTextField hasildes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
